# Generated by Django 4.0.3 on 2022-05-27 16:13
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('appDeustotil', '0002_remove_proyecto_tarea_tarea_proyecto'),
    ]
    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='contraseña',
            field=models.CharField(default='null', max_length=20),
        ),
    ]