# Generated by Django 4.0.3 on 2022-05-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustotil', '0003_contacto_empleado_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='appDeustotil.cliente'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='reponsable',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='appDeustotil.empleado'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='responsable',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='appDeustotil.empleado'),
        ),
    ]
